### ISSUE TITLE
Fix upstream mosquitto-client

### ISSUE THREAD

**Issue by linuxbasic** [ce-rust/cerk#88]
For the `cerk_port_mqtt_mostquitto` we are using the [mosquitto_client](https://docs.rs/mosquitto-client/0.1.5/mosquitto_client/) library. Unfortunately, the published version does not support the latest version of `libmossquitto` even though there is an open [pull request](https://github.com/stevedonovan/mosquitto-client/pull/10) to add support for a while.

Because of that, we are using not the version of the package published on crates.io but the patched one (see https://github.com/ce-rust/cerk/pull/77#discussion_r541687139). This prevents us from publishing the `cerk_port_mqtt_mostquitto`on crates.io

There are different ways to approach this issue:
- wait until https://github.com/stevedonovan/mosquitto-client/pull/10 is merged
- fork mosquitto_client and republish it on crates.io
- use [autogenerated binding](https://crates.io/crates/mosquitto-sys) directly

**Comment by Lazzaretti** [comment]
We forked the mosquitto-client and published it by ourself https://github.com/ce-rust/mosquitto-client-wrapper
